
project_id = "idpwghsuiaucwxjdzaqv"

[storage]
[storage.buckets]
[storage.buckets.covers]
public = true
allow_public_urls = true

[storage.buckets.podcasts]
public = true
allow_public_urls = true

[storage.buckets.call_records]
public = false
allow_public_urls = false
