
// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://idpwghsuiaucwxjdzaqv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImlkcHdnaHN1aWF1Y3d4amR6YXF2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDM4NTY0ODAsImV4cCI6MjA1OTQzMjQ4MH0.nEK9RRcMFsqrxwQqpBvPvXDjdGv6uKIVadwxIVK4gas";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);
