// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ffnjrliexdowbhtyhyrp.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6ImZmbmpybGlleGRvd2JodHloeXJwIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDMzNDIyNjgsImV4cCI6MjA1ODkxODI2OH0.0w2oD0gs5r_d_s67xrtEl6KpnDBrrpGB_hpflF-6DmU";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);